// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Handlebars;
    Handlebars = require('handlebars');
    return Handlebars.registerHelper('capitalize', function(string) {
      return string.capitalize();
    });
  });

}).call(this);
