// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var TargetsHierarchyCollection, publicTargetFixture;
    publicTargetFixture = require('fixtures/publicTarget');
    TargetsHierarchyCollection = require('src/TargetsHierarchyCollection');
    return describe('The Targets Hierarcy Collection', function() {
      var collection;
      collection = null;
      beforeEach(function() {
        var request;
        collection = new TargetsHierarchyCollection();
        jasmine.Ajax.useMock();
        collection.fetch();
        request = mostRecentAjaxRequest();
        return request.response(publicTargetFixture.success);
      });
      it('will have the api set to public', function() {
        expect(collection.options["public"]).toBeTruthy();
        return expect(collection.url()).toBe('/api/v1/public/target/?limit=0&sort=name');
      });
      return afterEach(function() {
        return collection = null;
      });
    });
  });

}).call(this);
