// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var TargetGroupViewModule, targetGroupFixtureItem;
    TargetGroupViewModule = require('src/views/TargetGroup');
    targetGroupFixtureItem = require('fixtures/targetGroupItem');
    return describe('Target Group Edit', function() {
      var requests, view, xhr;
      view = null;
      xhr = null;
      requests = [];
      beforeEach(function() {
        xhr = sinon.useFakeXMLHttpRequest();
        xhr.onCreate = function(requestXhr) {
          return requests.push(requestXhr);
        };
        return view = new TargetGroupViewModule.TargetGroupEdit({
          name: 'fooBar'
        });
      });
      describe('initialize', function() {
        return it('will call render', function() {
          sinon.spy(view, 'render');
          requests[0].respond.apply(requests[0], targetGroupFixtureItem.data);
          view.render.should.have.been.calledOnce;
          return view.render.restore();
        });
      });
      return afterEach(function() {
        if (view != null) {
          view.close();
        }
        xhr.restore();
        view = null;
        xhr = null;
        return requests = null;
      });
    });
  });

}).call(this);
