// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var TargetGroupModelModule;
    TargetGroupModelModule = require('src/models/TargetGroup');
    return describe('Target Group Model', function() {
      var model, xhr;
      model = null;
      xhr = null;
      beforeEach(function() {
        model = new TargetGroupModelModule.TargetGroup();
        return xhr = sinon.useFakeXMLHttpRequest();
      });
      it('should use name as id', function() {
        var name;
        model.url().should.equal(model.urlRoot);
        name = 'fooBar';
        model.set('name', name);
        return model.url().should.equal("" + model.urlRoot + name);
      });
      return afterEach(function() {
        xhr.restore();
        model = null;
        return xhr = null;
      });
    });
  });

}).call(this);
