// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Handlebars, _;
    Handlebars = require('handlebars');
    _ = require('underscore');
    Handlebars.registerHelper('comparator', function(options) {
      if (options.hash.expected === options.hash.actual) {
        return options.hash.ifTrue;
      } else {
        return options.hash.ifFalse;
      }
    });
    Handlebars.registerHelper('dateBetween', function(context, options) {
      var end, start;
      start = Date.create(options.hash.start).clone().rewind({
        seconds: 1
      });
      end = Date.create(options.hash.end).clone().advance({
        seconds: 1
      });
      if (Date.create(context).isBetween(start, end)) {
        return options.fn(this);
      } else {
        return options.inverse(this);
      }
    });
    return Handlebars.registerHelper('dateIterator', function(startDate, endDate, options) {
      var advancement, increment, out, outputFormat, unit;
      increment = options.hash.increment;
      unit = options.hash.unit;
      outputFormat = options.hash.outputFormat;
      out = '';
      startDate = Date.create(startDate).clone();
      while (startDate.isBefore(endDate)) {
        out += options.fn(_.extend({}, this, {
          currentValue: startDate.format(outputFormat),
          currentDate: startDate
        }));
        advancement = {};
        advancement[unit] = increment;
        startDate.advance(advancement);
      }
      return out;
    });
  });

}).call(this);
