source 'https://rubygems.org'
group :test do
  gem 'chefspec',         '~> 1.3'
  gem 'foodcritic',       '~> 2.1'
  gem 'strainer',         '~> 3.0'
  gem 'test-kitchen',     '~> 1.0.0.alpha'
#  gem 'kitchen-lxc',      '~> 0.0.1.beta1'
#  gem 'hipchat',          '~> 0.10.0'
  gem 'guard',            '~> 1.8'
  gem 'guard-foodcritic', '~> 1.0'
  gem 'guard-rspec',      '~> 3.0'
end
