// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Backbone;
    Backbone = require('backbone');
    return Backbone.View.prototype.close = function() {
      this.remove();
      this.unbind();
      if (this.onClose) {
        return this.onClose();
      }
    };
  });

}).call(this);
