alias gitup='git pull --rebase && git push'

# common (from zsh)
g=git
ga='git add'
gb='git branch'
gba='git branch -a'
gc='git commit -v'
gca='git commit -v -a'
gcl='git config --list'
gcm='git checkout master'
gco='git checkout'
gcount='git shortlog -sn'
gcp='git cherry-pick'
gd='git diff'
gf='git ls-files | grep'
ggpnp='git pull origin $(current_branch) && git push origin $(current_branch)'
ggpull='git pull origin $(current_branch)'
ggpush='git push origin $(current_branch)'
git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
gitup='git pull --rebase && git push'
gl='git pull'
glg='git log --stat --max-count=5'
glgg='git log --graph --max-count=5'
glgga='git log --graph --decorate --all'
gm='git merge'
gp='git push'
gpoat='git push origin --all && git push origin --tags'
gr='git remote'
grh='git reset HEAD'
grhh='git reset HEAD --hard'
grmv='git remote rename'
grrm='git remote remove'
grset='git remote set-url'
grt='cd $(git rev-parse --show-toplevel || echo ".")'
grup='git remote update'
grv='git remote -v'
gsd='git svn dcommit'
gsr='git svn rebase'
gss='git status -s'
gst='git status'
gup='git pull --rebase'
gwc='git whatchanged -p --abbrev-commit --pretty=medium'
