default[:ftp_admin][:user]		='ihr-deployer'
default[:ftp_admin][:group]		='ihr-deployer'
default[:ftp_admin][:deployer]	='ihr-deployer'
default[:ftp_admin][:ftp_admin_path]	='/data/apps/ftp_admin'
default[:ftp_admin][:repo]		='git@github.ihrint.com:OPS/ftp_admin.git'
default[:ftp_admin][:rev]		='27d0283aeb29708917e2542c66f5307717c1d0cc'
