default[:ftp_admin][:user]		='ftp_admin'
default[:ftp_admin][:group]		='ftp_admin'
default[:ftp_admin][:deployer]	='ihr-deployer'
default[:ftp_admin][:ftp_admin_path]	='/data/apps/ftp_admin'
default[:ftp_admin][:repo]		='git@github.ihrint.com:OPS/ftp_admin.git'
default[:ftp_admin][:rev]		='b2cab85cab7c181625257039bcd407e5b81fbcb2'
