default[:ftp_admin][:user]           ='ihr-deployer'
default[:ftp_admin][:group]          ='ihr-deployer'
default[:ftp_admin][:deployer]       ='ihr-deployer'
default[:ftp_admin][:ftp_admin_path] ='/data/apps/ftp_admin'
default[:ftp_admin][:repo]           ='git@github.ihrint.com:OPS/ftp_admin.git'
default[:ftp_admin][:rev]            ='42ae1e195af15e12432c74b4bcfa4491b2dab87b'
