#!/bin/bash
#
# Startup script for the Ingestion server
#
# Tested with Red Hat Enterprise Linux Server release 5.5
#
# chkconfig: 2345 85 15
#
# processname: ingestion
# pidfile: /var/run/ingestion.pid

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog="ingestion"
INGESTION="/opt/telecom/jboss/bin/ingestion.sh -c $prog"
PID_FILE=/var/run/ingestion.pid

start()
{
	echo -n $"Starting $prog: "
	/usr/bin/nohup $INGESTION start >> /dev/null 2>&1 &
        RETVAL=$?
	echo $! > $PID_FILE
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	kill $( /bin/cat $PID_FILE )
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status -p $PID_FILE $INGESTION
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
