// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(function(require) {
    var Backbone, originalClose, originalInitialize, rivets;
    Backbone = require('backbone');
    rivets = require('src/rivetsConfig');
    originalInitialize = Backbone.View.prototype.initialize;
    Backbone.View.prototype.initialize = function() {
      this.rivetsMap = {};
      return originalInitialize.call(this);
    };
    Backbone.View.prototype.setRivet = function(selectorString, modelMap) {
      var rivetView;
      rivetView = this.rivetsMap[selectorString];
      if (rivetView != null) {
        rivetView.unbind();
      }
      return this.rivetsMap[selectorString] = rivets.bind(this.$el.find(selectorString), modelMap);
    };
    originalClose = Backbone.View.prototype.close;
    return Backbone.View.prototype.close = function() {
      var name, rivetView, _ref;
      _ref = this.rivetsMap;
      for (name in _ref) {
        if (!__hasProp.call(_ref, name)) continue;
        rivetView = _ref[name];
        rivetView.unbind();
      }
      this.rivetsMap = null;
      return originalClose != null ? originalClose.call(this) : void 0;
    };
  });

}).call(this);
