// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Views, models;
    Views = require('multiDatePicker/views');
    models = require('multiDatePicker/models');
    return describe('Calendar View', function() {
      beforeEach(function() {
        this.chronologyModel = new models.ChronologyModel();
        this.calendarView = new Views.CalendarView({
          chronologyModel: this.chronologyModel
        });
        return $('body').append(this.calendarView.$el);
      });
      it('Will fill the view with calendar rendering', function() {
        this.calendarView.type = Views.CalendarView.BEGIN;
        this.chronologyModel.setDate(Date.create('07/04/2012'));
        this.chronologyModel.setActiveDate('07/06/2012');
        this.chronologyModel.setActiveDate('07/08/2012');
        expect($('.datepicker-days .day.active').length).toBe(3);
        expect($('.datepicker-days .day').last().text()).toBe('31');
        expect($('.datepicker-days thead th.switch').text()).toBe('July 2012');
        this.chronologyModel.setDate(Date.create('02/01/2024'));
        this.chronologyModel.setActiveDate('02/02/2024');
        expect($('.datepicker-days .day.active').text()).toBe('2');
        expect($('.datepicker-days .day').last().text()).toBe('29');
        return expect($('.datepicker-days thead th.switch').text()).toBe('February 2024');
      });
      return afterEach(function() {
        var calendarContainer;
        calendarContainer = $('.datepicker-days');
        if (calendarContainer.length) {
          return calendarContainer.remove();
        }
      });
    });
  });

}).call(this);
