// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var models;
    models = require('multiDatePicker/models');
    return describe('Chronology Model', function() {
      beforeEach(function() {
        return this.chronologyModel = new models.ChronologyModel();
      });
      return it('Will return the date range in a form usable by the API', function() {
        var converter, endDate, list, startDate;
        converter = function(date) {
          return Math.floor(date.valueOf() / 1000);
        };
        startDate = Date.create('06/01/2012');
        endDate = Date.create('07/02/2012');
        this.chronologyModel.setActiveDate(startDate);
        this.chronologyModel.setActiveDate(endDate);
        list = this.chronologyModel.getActiveDatesListInSeconds();
        return expect(list).toEqual([converter(startDate), converter(endDate)]);
      });
    });
  });

}).call(this);
