// Generated by CoffeeScript 1.3.3
(function() {
  var page, timer;

  page = require('webpage').create();

  timer = void 0;

  page.onConsoleMessage = function(msg) {
    console.log(msg);
    clearTimeout(timer);
    return timer = setTimeout(function() {
      return phantom.exit();
    }, 1000);
  };

  page.onError = function(msg, trace) {
    console.log(msg);
    return trace.forEach(function(item) {
      return console.log('  ', item.file, ':', item.line);
    });
  };

  page.open('http://localhost:8000/tests');

}).call(this);
