// Generated by CoffeeScript 1.3.3
(function() {

  define('common', ['notify', 'jquery.eventpri', 'bootstrap/bootstrap-button', 'bootstrap/bootstrap-dropdown', 'bootstrap/bootstrap-modal', 'bootstrap/bootstrap-transition', 'bootstrap/bootstrap-popover', 'bootstrap/bootstrap-tab', 'lib/json2', 'lib/chosen/chosen.jquery', 'lib/sugar-1.2.5.min', 'backboneViewClose', 'js/tests/lib/jquery.simulate', 'backboneViewClose', 'backboneViewRivets']);

  define(function(require) {
    var JSCovReporter, console, sinonChai;
    sinonChai = require('sinon-chai');
    JSCovReporter = require('JSCovReporter');
    require('lib/backboneExtensions/backbone.view.actionPanel');
    require('common');
    require('spec/RivetsBindingTest');
    require('spec/models/TargetGroupTest');
    require('spec/views/TargetGroupTest');
    chai.use(sinonChai);
    chai.should();
    console = window.console || function() {};
    window.notrack = true;
    return mocha.run(function() {
      var reporter;
      if (typeof window.__$coverObject !== 'undefined') {
        return reporter = new JSCovReporter({
          coverObject: window.__$coverObject
        });
      }
    });
  });

}).call(this);
