#!/bin/bash
#VERSION: 1.1

arg=$1
LOG=/var/log/ha-log

if [ "$arg" == "start" ]; then
    mountCheck=`mount |grep "/data"`
    if [ "X$mountCheck" != "X" ]; then
#################
# Already mounted
#################
        mountCheck=`mount |grep "/data" |grep "ro"`
        if [ "X$mountCheck" != "X" ]; then
################
# Try to remount rw
################
            mount -t ext4 -o remount,rw /dev/mapper/mpathbp1 /data
            RC=$?
            if [ $RC != 0 ]; then
                echo "Remount failed!: $RC" | tee -a $LOG
                exit 1
            fi

            mountCheck=`mount |grep "/data" |grep "rw"`
            if [ "X$mountCheck" == "X" ]; then
                echo "Failed to change volume to RW!" | tee -a $LOG
                exit 2
            else
                echo "datavol OK" | tee -a $LOG
                exit 0
        fi
        else
            echo "datavol OK" | tee -a $LOG
            exit 0
        fi
    else
#############
# Not mounted
#############
        mount -t ext4 -o rw /dev/mapper/mpathbp1 /data
        RC=$?
        if [ $RC != 0 ]; then
            echo "Mount failed!: $RC" | tee -a $LOG
            exit 3
        fi
        mountCheck=`mount |grep "/data" |grep "rw"`
        if [ "X$mountCheck" == "X" ]; then
            echo "Failed to change volume to RW!" | tee -a $LOG
            exit 4
        else
            echo "datavol OK" | tee -a $LOG
            df -h | tee -a $LOG
            exit 0
        fi
    fi
elif [ "$arg" == "stop" ]; then
    mountCheck=`mount |grep "/data" |grep "rw"`
    if [ "X$mountCheck" != "X" ]; then
        umount /data
        RC=$?
        if [ $RC != 0 ]; then
            echo "Umount failed!: $RC" | tee -a $LOG
            exit 5
        fi
    fi
    mountCheck=`mount |grep "/data"`
    if [ "X$mountCheck" != "X" ]; then
        echo "Failed to unmount volume!" | tee -a $LOG
        exit 6
    else
        echo "datavol OK" | tee -a $LOG
        exit 0
    fi
elif [ "$arg" == "status" ]; then
    mountCheck=`mount |grep "/data" |grep "rw"`
    if [ "X$mountCheck" != "X" ]; then
        echo "datavol OK" | tee -a $LOG
        exit 0
    else
        echo "datavol status FAIL" | tee -a $LOG
        exit 7
    fi
else
    echo "Usage: datavol [start|stop|status]" | tee -a $LOG
    exit 8
fi
