#!/bin/bash
#VERSION: 1.1

arg=$1

if [ "$arg" == "start" ]; then
       PID=`ps aux | grep /etc/ha.d/postgres_monitor_daemon | grep -v grep | awk '{print $2}'`
       if [ -n "$PID" ]
       then
         echo "Already running"
         exit 0
       fi

       /etc/ha.d/postgres_monitor_daemon &
       PID=$$
       sleep .5
       ps aux | grep ^root | awk '{print $2}' | grep ^$PID -q
       EC=$?
       if [ "$EC" -eq "0" ]
       then
         echo "OK"
         exit 0
       else
         echo "FAILED"
         exit 1
       fi

#echo ${PIPESTATUS[2]}

elif [ "$arg" == "stop" ]; then

    PID=`ps aux | grep /etc/ha.d/postgres_monitor_daemon | grep -v grep | awk '{print $2}'`
    if [ -n "$PID" ]
    then
       kill -9 $PID > /dev/null 2>&1
       EC=$?
       if [ "$EC" -eq "0" ]
       then
         echo "OK"
         exit 0
       else
         echo "FAILED"
         exit 2
       fi
    else
      echo "OK"
      exit 0
    fi

elif [ "$arg" == "status" ]; then

    PID=`ps aux | grep /etc/ha.d/postgres_monitor_daemon | grep -v grep | awk '{print $2}'`
    if [ -n "$PID" ]
    then
      echo "OK"
      exit 0
    else
      echo "FAIL"
      exit 3
    fi

else
    echo "Usage: datavol [start|stop|status]"
    exit 4
fi

